{

"appid" : 749820,
"items" : [

	{
	"itemdefid" : 21000,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Gadget, Device, Equipment",
	"name" : "Microwave Oven",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/ckMQYZq.png",
	"icon_url_large": "https://i.imgur.com/ckMQYZq.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"
	},

	{
	"itemdefid" : 21001,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Gadget, Device, Equipment",
	"name" : "Office Telephone",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/NYZlde7.png",
	"icon_url_large": "https://i.imgur.com/NYZlde7.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"
	},

	{
	"itemdefid" : 21002,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Gadget, Device, Equipment",
	"name" : "Mobile Phone",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/mBcLUUA.png",
	"icon_url_large": "https://i.imgur.com/mBcLUUA.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"
	},

	{
	"itemdefid" : 21003,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Gadget, Device, Equipment",
	"name" : "Walkie Talkie",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/pIhglQ6.png",
	"icon_url_large": "https://i.imgur.com/pIhglQ6.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"
	},

	{
	"itemdefid" : 21004,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Gadget, Device, Equipment",
	"name" : "Civilian Comm Radio",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/8Xznb1W.png",
	"icon_url_large": "https://i.imgur.com/8Xznb1W.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"
	},

	{
	"itemdefid" : 21005,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Gadget, Device, Equipment",
	"name" : "Military Comm Radio",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/wsvoq6L.png",
	"icon_url_large": "https://i.imgur.com/wsvoq6L.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"
	},

	{
	"itemdefid" : 21006,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Gadget, Device, Equipment",
	"name" : "Small Radio",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/QyilTqa.png",
	"icon_url_large": "https://i.imgur.com/QyilTqa.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"
	},

	{
	"itemdefid" : 21007,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Gadget, Device, Equipment",
	"name" : "Small Battery",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/3aXRg2F.png",
	"icon_url_large": "https://i.imgur.com/3aXRg2F.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"
	},

	{
	"itemdefid" : 21008,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Gadget, Device, Equipment",
	"name" : "Laptop Computer",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/WCLL9Xu.png",
	"icon_url_large": "https://i.imgur.com/WCLL9Xu.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"
	},

	{
	"itemdefid" : 21009,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Gadget, Device, Equipment",
	"name" : "Personal Computer Set",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/ch5NqRw.png",
	"icon_url_large": "https://i.imgur.com/ch5NqRw.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"
	},

	{
	"itemdefid" : 21010,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Gadget, Device, Equipment",
	"name" : "Lighter",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/0Bl6ets.png",
	"icon_url_large": "https://i.imgur.com/0Bl6ets.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"
	},

	{
	"itemdefid" : 21011,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Gadget, Device, Equipment",
	"name" : "Knife",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/3kPfSnB.png",
	"icon_url_large": "https://i.imgur.com/3kPfSnB.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"
	},

	{
	"itemdefid" : 21012,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Gadget, Device, Equipment",
	"name" : "Flashlight",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/9Rauwvo.png",
	"icon_url_large": "https://i.imgur.com/9Rauwvo.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"
	},

	{
	"itemdefid" : 21013,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Gadget, Device, Equipment",
	"name" : "Angle-Head Flashlight",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/JrXa4WY.png",
	"icon_url_large": "https://i.imgur.com/JrXa4WY.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"
	},

	{
	"itemdefid" : 21014,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Gadget, Device, Equipment",
	"name" : "Flask",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/S0K2FnM.png",
	"icon_url_large": "https://i.imgur.com/S0K2FnM.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"
	},

	{
	"itemdefid" : 21015,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Gadget, Device, Equipment",
	"name" : "Kerosene Lamp",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/EWQvHgu.png",
	"icon_url_large": "https://i.imgur.com/EWQvHgu.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"
	},

	{
	"itemdefid" : 21016,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Gadget, Device, Equipment",
	"name" : "Flat Screen TV",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/ly09KMi.png",
	"icon_url_large": "https://i.imgur.com/ly09KMi.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"
	},

	{
	"itemdefid" : 21017,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Gadget, Device, Equipment",
	"name" : "Fire Extinguisher",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/xyc1FSn.png",
	"icon_url_large": "https://i.imgur.com/xyc1FSn.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"
	}

]

}