{

"appid" : 749820,
"items" : [

	{
	"itemdefid" : 12000,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Empty Metal Can",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/TFFqJy5.png",
	"icon_url_large": "https://i.imgur.com/TFFqJy5.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:container"
	},

	{
	"itemdefid" : 12001,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Empty Plastic Can",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/VaayYWS.png",
	"icon_url_large": "https://i.imgur.com/VaayYWS.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:container"
	},

	{
	"itemdefid" : 12002,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Empty Barrel",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/50cIXBt.png",
	"icon_url_large": "https://i.imgur.com/50cIXBt.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:container"
	},

	{
	"itemdefid" : 12003,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Empty Small Gas Tank",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/W23KW2i.png",
	"icon_url_large": "https://i.imgur.com/W23KW2i.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:container"
	},

	{
	"itemdefid" : 12004,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Empty Gas Tank",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/zT6mcyB.png",
	"icon_url_large": "https://i.imgur.com/zT6mcyB.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:container"
	},

	{
	"itemdefid" : 12005,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Empty Liquid Tank",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/rACp2hE.png",
	"icon_url_large": "https://i.imgur.com/rACp2hE.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:container"
	},

	{
	"itemdefid" : 12006,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Empty Container",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/pLkr4nX.png",
	"icon_url_large": "https://i.imgur.com/pLkr4nX.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:container"
	},

	{
	"itemdefid" : 12007,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Gasoline (Can)",
	"description" : "20 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/NlokxQ3.png",
	"icon_url_large": "https://i.imgur.com/NlokxQ3.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12008,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Gasohol (Can)",
	"description" : "20 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/pURwIKZ.png",
	"icon_url_large": "https://i.imgur.com/pURwIKZ.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12009,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Diesel (Can)",
	"description" : "20 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/URMpWN8.png",
	"icon_url_large": "https://i.imgur.com/URMpWN8.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12010,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Biodiesel (Can)",
	"description" : "20 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/Lw0ynah.png",
	"icon_url_large": "https://i.imgur.com/Lw0ynah.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12011,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Jet Fuel (Can)",
	"description" : "20 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/E2UDug1.png",
	"icon_url_large": "https://i.imgur.com/E2UDug1.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12012,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Jet Biofuel (Can)",
	"description" : "20 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/u4bkagx.png",
	"icon_url_large": "https://i.imgur.com/u4bkagx.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12013,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Kerosene (Can)",
	"description" : "20 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/XVXXl3P.png",
	"icon_url_large": "https://i.imgur.com/XVXXl3P.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12014,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Crude Oil (Barrel)",
	"description" : "200 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/TdZSqCq.png",
	"icon_url_large": "https://i.imgur.com/TdZSqCq.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12015,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Heavy Oil (Barrel)",
	"description" : "200 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/WQckzFt.png",
	"icon_url_large": "https://i.imgur.com/WQckzFt.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12016,
	"type" : "item",
	"display_type" : "Industrial Supply",
	"name" : "Goods Container",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/SWB288p.png",
	"icon_url_large": "https://i.imgur.com/SWB288p.png",
	"tags":"industry:goods"
	},

	{
	"itemdefid" : 12017,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Gasoline (Barrel)",
	"description" : "200 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/mgAq129.png",
	"icon_url_large": "https://i.imgur.com/mgAq129.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12018,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Gasohol (Barrel)",
	"description" : "200 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/LlNuJJE.png",
	"icon_url_large": "https://i.imgur.com/LlNuJJE.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12019,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Diesel (Barrel)",
	"description" : "200 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/J9atkQ0.png",
	"icon_url_large": "https://i.imgur.com/J9atkQ0.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12020,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Biodiesel (Barrel)",
	"description" : "200 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/Bn9HxEC.png",
	"icon_url_large": "https://i.imgur.com/Bn9HxEC.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12021,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Jet Fuel (Barrel)",
	"description" : "200 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/Nk4Gvrl.png",
	"icon_url_large": "https://i.imgur.com/Nk4Gvrl.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12022,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Jet Biofuel (Barrel)",
	"description" : "200 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/PTB7Dt5.png",
	"icon_url_large": "https://i.imgur.com/PTB7Dt5.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12023,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Kerosene (Barrel)",
	"description" : "200 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/HiMo0Qn.png",
	"icon_url_large": "https://i.imgur.com/HiMo0Qn.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12024,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Gasoline (Tank)",
	"description" : "20,000 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/PcZXS2J.png",
	"icon_url_large": "https://i.imgur.com/PcZXS2J.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12025,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Gasohol (Tank)",
	"description" : "20,000 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/oaOml3n.png",
	"icon_url_large": "https://i.imgur.com/oaOml3n.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12026,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Diesel (Tank)",
	"description" : "20,000 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/EGAzzyQ.png",
	"icon_url_large": "https://i.imgur.com/EGAzzyQ.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12027,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Biodiesel (Tank)",
	"description" : "20,000 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/VWkufkE.png",
	"icon_url_large": "https://i.imgur.com/VWkufkE.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12028,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Jet Fuel (Tank)",
	"description" : "20,000 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/zw9sFdb.png",
	"icon_url_large": "https://i.imgur.com/zw9sFdb.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12029,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Jet Biofuel (Tank)",
	"description" : "20,000 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/EimuR4X.png",
	"icon_url_large": "https://i.imgur.com/EimuR4X.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12030,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Kerosene (Tank)",
	"description" : "20,000 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/jvjXJ8Q.png",
	"icon_url_large": "https://i.imgur.com/jvjXJ8Q.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12031,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "CNG (Small Tank)",
	"description" : "50 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/aI6YHDt.png",
	"icon_url_large": "https://i.imgur.com/aI6YHDt.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12032,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "LPG (Small Tank)",
	"description" : "50 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/fXaemGE.png",
	"icon_url_large": "https://i.imgur.com/fXaemGE.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12033,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "CNG (Tank)",
	"description" : "20,000 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/jGUcYW6.png",
	"icon_url_large": "https://i.imgur.com/jGUcYW6.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12034,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "LPG (Tank)",
	"description" : "20,000 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/tOsUrRz.png",
	"icon_url_large": "https://i.imgur.com/tOsUrRz.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12035,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Gasoline Engine Motor Oil",
	"description" : "10 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/OC7VTKV.png",
	"icon_url_large": "https://i.imgur.com/OC7VTKV.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12036,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Diesel Engine Motor Oil",
	"description" : "10 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/iqJ8JM8.png",
	"icon_url_large": "https://i.imgur.com/iqJ8JM8.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12037,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Grease (Can)",
	"description" : "10 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/g7c73da.png",
	"icon_url_large": "https://i.imgur.com/g7c73da.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12038,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Crude Oil (Tank)",
	"description" : "20,000 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/WFWEip4.png",
	"icon_url_large": "https://i.imgur.com/WFWEip4.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12039,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Heavy Oil (Tank)",
	"description" : "20,000 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/mC6b5X0.png",
	"icon_url_large": "https://i.imgur.com/mC6b5X0.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:petroleum"
	},

	{
	"itemdefid" : 12040,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Water (Tank)",
	"description" : "20,000 Litres",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/5UPlrLt.png",
	"icon_url_large": "https://i.imgur.com/5UPlrLt.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:water"
	},

	{
	"itemdefid" : 12041,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Water (Gallon)",
	"description" : "20",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/EvzhHVb.png",
	"icon_url_large": "https://i.imgur.com/EvzhHVb.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:water"
	},

	{
	"itemdefid" : 12042,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Industrial Supply",
	"name" : "Empty Mini Container",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/xjRCjdV.png",
	"icon_url_large": "https://i.imgur.com/xjRCjdV.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000",
	"tags":"industry:container"
	},

	{
	"itemdefid" : 12043,
	"type" : "item",
	"display_type" : "Industrial Supply",
	"name" : "Goods Mini Container",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/bRlGhnE.png",
	"icon_url_large": "https://i.imgur.com/bRlGhnE.png"
	},

	{
	"itemdefid" : 12044,
	"type" : "item",
	"display_type" : "Industrial Supply",
	"name" : "Goods Plastic Can",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/LcqrdAk.png",
	"icon_url_large": "https://i.imgur.com/LcqrdAk.png"
	},

	{
	"itemdefid" : 12045,
	"type" : "item",
	"display_type" : "Industrial Supply",
	"name" : "Goods Metal Can",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/DgKVBVh.png",
	"icon_url_large": "https://i.imgur.com/DgKVBVh.png"
	},

	{
	"itemdefid" : 12046,
	"type" : "item",
	"display_type" : "Industrial Supply",
	"name" : "Goods Barrel",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/09KG7c2.png",
	"icon_url_large": "https://i.imgur.com/09KG7c2.png"
	},

	{
	"itemdefid" : 12047,
	"type" : "item",
	"display_type" : "Industrial Supply",
	"name" : "Goods Small Gas Tank",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/SmMg5wY.png",
	"icon_url_large": "https://i.imgur.com/SmMg5wY.png"
	},

	{
	"itemdefid" : 12048,
	"type" : "item",
	"display_type" : "Industrial Supply",
	"name" : "Goods Gas Tank",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/R39IkQj.png",
	"icon_url_large": "https://i.imgur.com/R39IkQj.png"
	},

	{
	"itemdefid" : 12049,
	"type" : "item",
	"display_type" : "Industrial Supply",
	"name" : "Goods Liquid Tank",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/o6aYTWr.png",
	"icon_url_large": "https://i.imgur.com/o6aYTWr.png"
	},

	{
	"itemdefid" : 12050,
	"type" : "item",
	"display_type" : "Industrial Supply",
	"name" : "Empty Goods Box",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/DfvB9SL.png",
	"icon_url_large": "https://i.imgur.com/DfvB9SL.png"
	},

	{
	"itemdefid" : 12051,
	"type" : "item",
	"display_type" : "Industrial Supply",
	"name" : "Goods Box",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/7lfbL7E.png",
	"icon_url_large": "https://i.imgur.com/7lfbL7E.png"
	}


]

}