{

"appid" : 749820,
"items" : [

	{
	"itemdefid" : 9000,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Placeable",
	"name" : "Camping Tent",
	"description" : "The World is Home.",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/GgUUpIJ.png",
	"icon_url_large": "https://i.imgur.com/GgUUpIJ.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"	
	},

	{
	"itemdefid" : 9001,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Placeable",
	"name" : "Small Generator",
	"description" : "Provide enough energy for a TV.",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/yTycNOx.png",
	"icon_url_large": "https://i.imgur.com/yTycNOx.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"	
	},

	{
	"itemdefid" : 9002,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Placeable",
	"name" : "Solar Panel Stand",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/x56afV5.png",
	"icon_url_large": "https://i.imgur.com/x56afV5.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"	
	},

	{
	"itemdefid" : 9003,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Placeable",
	"name" : "Solar Panel",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/MMTcwtV.png",
	"icon_url_large": "https://i.imgur.com/MMTcwtV.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"	
	},

	{
	"itemdefid" : 9004,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Placeable",
	"name" : "Recycle Trash Can (Metal)",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/YyPnY0B.png",
	"icon_url_large": "https://i.imgur.com/YyPnY0B.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"	
	},

	{
	"itemdefid" : 9005,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Placeable",
	"name" : "Recycle Trash Can (Paper)",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/fPbjm9q.png",
	"icon_url_large": "https://i.imgur.com/fPbjm9q.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"	
	},

	{
	"itemdefid" : 9006,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Placeable",
	"name" : "Recycle Trash Can (Glass)",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/ox9cNm7.png",
	"icon_url_large": "https://i.imgur.com/ox9cNm7.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"	
	},

	{
	"itemdefid" : 9007,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Placeable",
	"name" : "Recycle Trash Can (Plastic)",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/741K0lS.png",
	"icon_url_large": "https://i.imgur.com/741K0lS.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"	
	},

	{
	"itemdefid" : 9008,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Placeable",
	"name" : "Recycle Trash Can (Organic)",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/Zvbqv2e.png",
	"icon_url_large": "https://i.imgur.com/Zvbqv2e.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"	
	},

	{
	"itemdefid" : 9009,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Placeable",
	"name" : "Office Table Set",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/RfP2ILt.png",
	"icon_url_large": "https://i.imgur.com/RfP2ILt.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"	
	},

	{
	"itemdefid" : 9010,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Placeable",
	"name" : "Portable Toilet",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/owtBZme.png",
	"icon_url_large": "https://i.imgur.com/owtBZme.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"	
	},

	{
	"itemdefid" : 9011,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Placeable",
	"name" : "Shared Locker",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/zTLRzug.png",
	"icon_url_large": "https://i.imgur.com/zTLRzug.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"	
	},

	{
	"itemdefid" : 9012,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Placeable",
	"name" : "Personal Locker",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/Kw8YAlI.png",
	"icon_url_large": "https://i.imgur.com/Kw8YAlI.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"	
	},

	{
	"itemdefid" : 9013,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Placeable",
	"name" : "Metal Shelf",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/7SKUU10.png",
	"icon_url_large": "https://i.imgur.com/7SKUU10.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"	
	},

	{
	"itemdefid" : 9014,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Placeable",
	"name" : "Flood Light",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/ZyzCBHK.png",
	"icon_url_large": "https://i.imgur.com/ZyzCBHK.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"	
	},

	{
	"itemdefid" : 9015,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Placeable",
	"name" : "Flood Light Stand",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/OEtbXtC.png",
	"icon_url_large": "https://i.imgur.com/OEtbXtC.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"	
	},

	{
	"itemdefid" : 9016,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Placeable",
	"name" : "Cooking Station",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/2Ki96QP.png",
	"icon_url_large": "https://i.imgur.com/2Ki96QP.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"	
	},

	{
	"itemdefid" : 9017,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Placeable",
	"name" : "Refrigerator",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/ZizGbMn.png",
	"icon_url_large": "https://i.imgur.com/ZizGbMn.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"	
	},

	{
	"itemdefid" : 9018,
	"type" : "item",
	"promo" : "manual",
	"display_type" : "Placeable",
	"name" : "Safe",
	"description" : "",
	"name_color" : "FFFFFF",
	"background_color" : "DDA373",
	"tradable" : true,
	"marketable" : true,
	"icon_url": "https://i.imgur.com/Ig5E9bi.png",
	"icon_url_large": "https://i.imgur.com/Ig5E9bi.png",
	"drop_interval" : 1,
	"use_drop_window" : true,
	"drop_window" : "1440",
	"drop_max_per_window" : "1000"	
	}

]

}